#!/bin/sh

echo "Initializing Genesis"

git submodule init              && \
git submodule update            && \
cd src/assets/css/              && \
git pull origin master          && \
cd ../../../                    && \
rm -rf .git/                    && \
rm -rf .gitmodules              && \
rm -rf src/assets/css/.git

echo "Genesis has been successfully initialized"

rm init
